### 20143692_KangKyeungseok
### Machine Learning Assignment 10
### Build a binary classifier for each digit against all the other digits at MNIST dataset.

In [25]:
import numpy as np

file_data_train = "mnist_train.csv"
file_data_test  = "mnist_test.csv"

h_data_train    = open(file_data_train, "r")
h_data_test     = open(file_data_test, "r")

data_train      = h_data_train.readlines()
data_test       = h_data_test.readlines()

h_data_train.close()
h_data_test.close()

size_row    = 28    # height of the image
size_col    = 28    # width of the image

num_train   = len(data_train)   # number of training images
num_test    = len(data_test)    # number of testing images

In [26]:
p = np.array([125, 625])

In [27]:

def f(x, p_r, r):
    
    y = np.empty(p_r, dtype=float)

    for i in range(0, p_r):
        y[i] = np.dot(r[i].T, x)
    
    return y

In [28]:
def argmax(x):
    
    max_x = -9999
    
    idx = 0
    
    for i in range(0, 10):
        if(max_x < x[i]):
            max_x = x[i]
            idx = i
            
    return idx

In [29]:
def normalize(data):

    data_normalized = (data - min(data)) / (max(data) - min(data))

    return(data_normalized)

In [30]:

list_image_train    = np.empty((size_row * size_col, num_train), dtype=float)
list_label_train    = np.empty(num_train, dtype=int)

list_image_test     = np.empty((size_row * size_col, num_test), dtype=float)
list_label_test     = np.empty(num_test, dtype=int)

In [31]:
def get_optimal(select,p, n, r):
    count = 0
    for line in data_train:

        line_data   = line.split(',')
        label       = line_data[0]
        im_vector   = np.asfarray(line_data[1:])
        im_vector   = normalize(im_vector)

        if(label == str(select)):
            list_label_train[count] = 1
        else :
                list_label_train[count] = -1

        list_image_train[:, count]  = im_vector 

        count += 1
    
    A = np.empty((num_train,p[n]), dtype=float)

    for i in range(0, num_train):
        A[i] = f(list_image_train[:,i], p[n], r)
        
    optimal = np.dot(np.dot(np.linalg.inv(np.dot(A.T,A)),A.T),list_label_train[:])
    
    return optimal

In [32]:
count = 0

for line in data_test:

    line_data   = line.split(',')
    label       = line_data[0]
    im_vector   = np.asfarray(line_data[1:])
    im_vector   = normalize(im_vector)

    for j in range(0, 10):
        if(label == str(j)):
            list_label_test[count] = j
        
    list_image_test[:, count]   = im_vector    

    count += 1

In [43]:

for n in range(0, 1):
    
    c_m = np.zeros((10, 10), dtype=int)
    
    r = np.random.normal(0, 1, (p[n],size_row*size_col))
    
    optimal = np.empty((10,p[n]),dtype=float)
    
    for i in range(0, 10):
        optimal[i] = get_optimal(i, p, n, r)
        

    X = np.empty((num_train, p[n]), dtype=float)
    
    for i in range(0, num_train):
        X[i] = f(list_image_train[:,i], p[n],r)
        
    tp = 0
    fp = 0
    fn = 0
    tn = 0
    
    for i in range(0, num_train) :
        
        guesses = np.zeros(10, dtype=float)
        
        for j in range(0, 10):
            guesses[j] = np.dot(X[i], optimal[j].T)
            
        guess = argmax(guesses)
            
        for l in range(0, 10):
            for k in range(0, 10):
                if(guess == l and list_label_train[i] == k):
                    c_m[l][k] = c_m[l][k] + 1
                    if(l == k):
                        tp = tp + 1
                    elif(l > k):
                        fp = fp + 1
                    elif(l < k):
                        fn = fn + 1
    print("Compute an optimal model parameter using the training dataset for each classifier f_d(x, w)")                    
    print(c_m)
    print(" Compute (1) true positive rate, (2) error rate using (1) training dataset")
    print("(1) true positive rate: {:.3f}\(2) error rate: {:.3f}".format((tp/(tp+fn)),(fn+fp)/(tp+fp+tn+fn)))



Compute an optimal model parameter using the training dataset for each classifier f_d(x, w)
[[   0   82    0    0    0    0    0    0    0    0]
 [   0   87    0    0    0    0    0    0    0    0]
 [   0   49    0    0    0    0    0    0    0    0]
 [   0  110    0    0    0    0    0    0    0    0]
 [   0  392    0    0    0    0    0    0    0    0]
 [   0   29    0    0    0    0    0    0    0    0]
 [   0   14    0    0    0    0    0    0    0    0]
 [   0  460    0    0    0    0    0    0    0    0]
 [   0   57    0    0    0    0    0    0    0    0]
 [   0 4669    0    0    0    0    0    0    0    0]]
 Compute (1) true positive rate, (2) error rate using (1) training dataset
(1) true positive rate: 0.515\(2) error rate: 0.985


In [44]:
for n in range(0, 1):
    
    c_m = np.zeros((10, 10), dtype=int)
    
    r = np.random.normal(0, 1, (p[n],size_row*size_col))
    
    optimal = np.empty((10,p[n]),dtype=float)
    
    for i in range(0, 10):
        optimal[i] = get_optimal(i, p, n, r)
        

    X = np.empty((num_test, p[n]), dtype=float)
    
    for i in range(0, num_test):
        X[i] = f(list_image_test[:,i], p[n],r)
        
    tp = 0
    fp = 0
    fn = 0
    tn = 0
    
    for i in range(0, num_test) :
        
        guesses = np.zeros(10, dtype=float)
        
        for j in range(0, 10):
            guesses[j] = np.dot(X[i], optimal[j].T)
            
        guess = argmax(guesses)
            
        for l in range(0, 10):
            for k in range(0, 10):
                if(guess == l and list_label_test[i] == k):
                    c_m[l][k] = c_m[l][k] + 1
                    if(l == k):
                        tp = tp + 1
                    elif(l > k):
                        fp = fp + 1
                    elif(l < k):
                        fn = fn + 1


    print(" Compute (1) true positive rate, (2) error rate using (2) testing dataset")
    print("(1) true positive rate: {:.3f}\(2) error rate: {:.3f}".format((tp/(tp+fn)),(fn+fp)/(tp+fp+tn+fn)))

 Compute (1) true positive rate, (2) error rate using (2) testing dataset
(1) true positive rate: 0.898\(2) error rate: 0.164


(1) true positive rate: 0.553072625698324\(2) error rate: 0.983
